# ================================
# Build stage
# ================================
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY shopitems shopitems
WORKDIR /app/shopitems

RUN mvn clean package -DskipTests

# ================================
# Runtime stage
# ================================
FROM eclipse-temurin:17-jre
WORKDIR /app

# Quarkus uber-jar output
COPY --from=build /app/shopitems/target/*-runner.jar app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
